controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_admin_reservation_index_select:
    path: /admin/reservation/select
    controller: App\Controller\AdminReservationController::select
    methods: [GET]
admin_reservation_delete_confirmation:
    path: /admin_reservation/delete_confirmation
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'admin_reservation/delete_confirmation.html.twig'
admin_reservation_update_confirmation:
    path: /admin_reservation/update_confirmation
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'admin_reservation/update_confirmation.html.twig'