<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvJepme\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvJepme/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvJepme.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvJepme\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvJepme\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvJepme',
    'container.build_id' => 'b219a79a',
    'container.build_time' => 1682616900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvJepme');
